quarkus.thread-pool.shutdown-timeout=30s

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus
quarkus.datasource.devservices.port=5432


#%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/orders_dev
#%test.quarkus.datasource.devservices.enabled=true
#%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:5432/orders

quarkus.datasource.devservices.show-logs=true

## App config
app.order.max-items=50
app.order.default-currency=BRL
app.order.retry.max-attempts=3

## Flyway

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migrations
# Connection pool (Agroal)
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.idle-removal-interval=PT5M
quarkus.datasource.jdbc.max-lifetime=PT30M
quarkus.datasource.jdbc.acquisition-timeout=PT5S

quarkus.hibernate-orm.database.generation=none
%dev.quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.log.sql=true